package:
  name: phawd
  version: 0.2

source:
  path: ..

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vvv

requirements:
  build:
    - "{{ compiler('cxx') }}"
    - cmake
    - ninja

  host:
    - python
    - pip !=22.1.0

  run:
    - python

test:
  requires:
    - pytest
  imports:
    - phawd
  source_files:
    - tests
  commands:
    - python -m pytest

about:
  summary: python binding for software(Parameter Handler And Waveform Displayer)
  license_file: LICENSE
